backend:
  name: github
  repo: "JaxPlays-Inc/jaxplays.org" # Path to your GitHub repository
  # optional, defaults to master
  branch: master
  base_url: https://hushed-dashing-iguanacolossus.glitch.me/

logo_url: https://jaxplays.org/JaxPlaysLogo.svg
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/media/uploads" # Media files will be stored in the repo under static/media/uploads
public_folder: "/media/uploads" # The src attribute for uploaded media will begin with /media/uploads

# permalinks:
#   news: "/:section/:year/:month/:day/:slug/"
#   reviews: "/:section/:year/:month/:day/:slug/"
#   editorials: "/:section/:year/:month/:day/:slug/"

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "news/{{slug}}" # The path to the page for previewing documents
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Featured Image Caption", name: "featured_image_caption", widget: "string", required: false}
      - {label: "Featured Image Alt Text", name: "featured_image_alt", widget: "string", required: false}
      - {label: "Featured Image Attribute", name: "featured_image_attr", widget: "string", required: false}
      - {label: "Featured Image Attribute Link", name: "featured_image_attr_link", widget: "string", required: false}      
      - {label: "SEO Description", name: "description", widget: "string", required: false}      
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
  - name: "editorials" # Used in routes, e.g., /admin/collections/blog
    label: "Editorials" # Used in the UI
    folder: "content/editorials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "preview/editorials/{{slug}}" # The path to the page for previewing documents
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Featured Image Caption", name: "featured_image_caption", widget: "string", required: false}
      - {label: "Featured Image Alt Text", name: "featured_image_alt", widget: "string", required: false}
      - {label: "Featured Image Attribute", name: "featured_image_attr", widget: "string", required: false}
      - {label: "Featured Image Attribute Link", name: "featured_image_attr_link", widget: "string", required: false}      
      - {label: "SEO Description", name: "description", widget: "string", required: false}      
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
  - name: "reviews" # Used in routes, e.g., /admin/collections/blog
    label: "Reviews" # Used in the UI
    folder: "content/reviews" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "preview/reviews/{{slug}}" # The path to the page for previewing documents
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Featured Image Caption", name: "featured_image_caption", widget: "string", required: false}
      - {label: "Featured Image Alt Text", name: "featured_image_alt", widget: "string", required: false}
      - {label: "Featured Image Attribute", name: "featured_image_attr", widget: "string", required: false}
      - {label: "Featured Image Attribute Link", name: "featured_image_attr_link", widget: "string", required: false}      
      - {label: "SEO Description", name: "description", widget: "string", required: false}      
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Production", name: "production", widget: "string", required: false}
      - {label: "Theatre", name: "theatre", widget: "string", required: false}
      - {label: "Cast", name: "cast", widget: "list", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
  - name: "people" # Used in routes, e.g., /admin/collections/blog
    label: "People" # Used in the UI
    folder: "content/people" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "preview/people/{{slug}}" # The path to the page for previewing documents
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Aliases", name: "aliases", widget: "list", required: false}
      - {label: "Other Names", name: "other_names", widget: "list", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Featured Image Attribute", name: "featured_image_attr", widget: "string", required: false}
      - {label: "Featured Image Caption", name: "featured_image_caption", widget: "string", required: false}
      - {label: "Featured Image Alt Text", name: "featured_image_alt", widget: "string", required: false}
      - {label: "Facebook", name: "Facebook", widget: "string", required: false}
      - {label: "Twitter", name: "Twitter", widget: "string", required: false}
      - {label: "Instagram", name: "Instagram", widget: "string", required: false}
      - {label: "LinkedIn", name: "LinkedIn", widget: "string", required: false}
      - {label: "IBDB", name: "IBDB", widget: "string", required: false}
      - {label: "IMDb", name: "IMDB", widget: "string", required: false}
      - {label: "Website", name: "Website", widget: "string", required: false}
      - {label: "Birth Date", name: "birth_date", widget: "datetime", required: false}
      - {label: "Birth Place", name: "birth_place", widget: "string", required: false}
      - {label: "Death Date", name: "death_date", widget: "datetime", required: false}
      - {label: "Death Place", name: "death_place", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}